# SKIP CATEGORIES
# Used by capture-size-audit.sh to explain what is intentionally skipped.
# Format: "PATH | REASON"

SKIP_ENTRIES=(
  "<docker-data-dir>/DockerDesktop  | Docker.raw virtual disk — large; rebuild images from registries post-reimage"
  "<ide-plugin-cache>/github-copilot-intellij | IDE Copilot plugin cache — reinstall post-reimage"
  "~/.gradle                        | Gradle dependency cache — large; re-downloads on first build"
  "~/.m2                            | Maven dependency cache — re-downloads on first build"
  "~/.cache                         | Assorted tool caches (gh, npm, copilot, pluginVerifier)"
  "~/.npm                           | npm download cache"
  "~/.nvm                           | Node Version Manager install — reinstall nvm then: nvm install <version>"
  "~/.rbenv                         | Ruby version manager — reinstall rbenv then restore .ruby-version files"
  "~/.sdkman                        | SDKMAN Java/Kotlin/Gradle version manager — reinstall then: sdk install <candidate>"
  "~/.android                       | Android SDK cache"
  "~/.aspnet                        | .NET DataProtection keys — regenerated automatically"
  "JDK lib/security/cacerts           | Default JDK truststore — do not copy wholesale; capture corporate jssecacerts instead"
  "~/.hawtjni                       | JNI native library cache"
  "~/.gem                           | Ruby gem cache — reinstall via Gemfile"
  "~/.local                         | Mostly generated state and bin symlinks"
  "~/.parallel                      | GNU parallel temp files"
  "~/.config/github-copilot         | GitHub Copilot cache"
  "~/.azure/logs                    | Azure CLI logs"
  "~/.azure/telemetry               | Azure CLI telemetry"
  "~/.copilot/logs                  | Copilot session logs"
  "~/.copilot/history-session-state | Copilot session history state"
  "~/.copilot/session-state         | Copilot active session state"
  "Downloads/*.dmg *.pkg *.zip      | Installers — re-download post-reimage"
  "~/.Trash                         | Trash — empty before reimage"
  "~/Library/Logs/OneDrive/*/general.keystore | OneDrive internal TLS cert store — auto-generated, skip"
)
